// Mocks generated by Mockito 5.4.6 from annotations
// in recipe/test/features/recipes/presentation/bloc/favorites/favorites_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:recipe/features/recipes/domain/repositories/recipe_repository.dart'
    as _i2;
import 'package:recipe/features/recipes/domain/usecases/get_favorites.dart'
    as _i3;
import 'package:recipe/features/recipes/domain/usecases/toggle_favorite_status.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRecipeRepository_0 extends _i1.SmartFake
    implements _i2.RecipeRepository {
  _FakeRecipeRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetFavorites].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetFavorites extends _i1.Mock implements _i3.GetFavorites {
  MockGetFavorites() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.RecipeRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeRecipeRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.RecipeRepository);

  @override
  _i4.Future<List<String>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i4.Future<List<String>>.value(<String>[]),
          )
          as _i4.Future<List<String>>);
}

/// A class which mocks [ToggleFavoriteStatus].
///
/// See the documentation for Mockito's code generation for more information.
class MockToggleFavoriteStatus extends _i1.Mock
    implements _i5.ToggleFavoriteStatus {
  MockToggleFavoriteStatus() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.RecipeRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeRecipeRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.RecipeRepository);

  @override
  _i4.Future<void> call(String? recipeId, bool? isCurrentlyFavorite) =>
      (super.noSuchMethod(
            Invocation.method(#call, [recipeId, isCurrentlyFavorite]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
