// Mocks generated by Mockito 5.4.6 from annotations
// in recipe/test/features/recipes/presentation/bloc/recipe_list/recipe_list_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:recipe/features/recipes/domain/entities/category.dart' as _i7;
import 'package:recipe/features/recipes/domain/entities/recipe.dart' as _i5;
import 'package:recipe/features/recipes/domain/repositories/recipe_repository.dart'
    as _i2;
import 'package:recipe/features/recipes/domain/usecases/get_areas.dart' as _i8;
import 'package:recipe/features/recipes/domain/usecases/get_categories.dart'
    as _i6;
import 'package:recipe/features/recipes/domain/usecases/get_recipes.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRecipeRepository_0 extends _i1.SmartFake
    implements _i2.RecipeRepository {
  _FakeRecipeRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetRecipes].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetRecipes extends _i1.Mock implements _i3.GetRecipes {
  MockGetRecipes() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.RecipeRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeRecipeRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.RecipeRepository);

  @override
  _i4.Future<List<_i5.Recipe>> call({String? query}) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#query: query}),
            returnValue: _i4.Future<List<_i5.Recipe>>.value(<_i5.Recipe>[]),
          )
          as _i4.Future<List<_i5.Recipe>>);
}

/// A class which mocks [GetCategories].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCategories extends _i1.Mock implements _i6.GetCategories {
  MockGetCategories() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.RecipeRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeRecipeRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.RecipeRepository);

  @override
  _i4.Future<List<_i7.Category>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i4.Future<List<_i7.Category>>.value(<_i7.Category>[]),
          )
          as _i4.Future<List<_i7.Category>>);
}

/// A class which mocks [GetAreas].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAreas extends _i1.Mock implements _i8.GetAreas {
  MockGetAreas() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.RecipeRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeRecipeRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.RecipeRepository);

  @override
  _i4.Future<List<String>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i4.Future<List<String>>.value(<String>[]),
          )
          as _i4.Future<List<String>>);
}
