// Mocks generated by Mockito 5.4.6 from annotations
// in recipe/test/features/recipes/data/recipe_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:recipe/features/recipes/data/datasources/local/recipe_local_data_source.dart'
    as _i6;
import 'package:recipe/features/recipes/data/datasources/remote/recipe_remote_data_source.dart'
    as _i3;
import 'package:recipe/features/recipes/data/models/category_model.dart' as _i5;
import 'package:recipe/features/recipes/data/models/recipe_model.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRecipeModel_0 extends _i1.SmartFake implements _i2.RecipeModel {
  _FakeRecipeModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RecipeRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecipeRemoteDataSource extends _i1.Mock
    implements _i3.RecipeRemoteDataSource {
  MockRecipeRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.RecipeModel>> getRecipes({String? query}) =>
      (super.noSuchMethod(
            Invocation.method(#getRecipes, [], {#query: query}),
            returnValue: _i4.Future<List<_i2.RecipeModel>>.value(
              <_i2.RecipeModel>[],
            ),
          )
          as _i4.Future<List<_i2.RecipeModel>>);

  @override
  _i4.Future<_i2.RecipeModel> getRecipeDetails(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getRecipeDetails, [id]),
            returnValue: _i4.Future<_i2.RecipeModel>.value(
              _FakeRecipeModel_0(
                this,
                Invocation.method(#getRecipeDetails, [id]),
              ),
            ),
          )
          as _i4.Future<_i2.RecipeModel>);

  @override
  _i4.Future<List<_i5.CategoryModel>> getCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getCategories, []),
            returnValue: _i4.Future<List<_i5.CategoryModel>>.value(
              <_i5.CategoryModel>[],
            ),
          )
          as _i4.Future<List<_i5.CategoryModel>>);

  @override
  _i4.Future<List<String>> getAreas() =>
      (super.noSuchMethod(
            Invocation.method(#getAreas, []),
            returnValue: _i4.Future<List<String>>.value(<String>[]),
          )
          as _i4.Future<List<String>>);

  @override
  _i4.Future<List<_i2.RecipeModel>> filterByCategory(String? category) =>
      (super.noSuchMethod(
            Invocation.method(#filterByCategory, [category]),
            returnValue: _i4.Future<List<_i2.RecipeModel>>.value(
              <_i2.RecipeModel>[],
            ),
          )
          as _i4.Future<List<_i2.RecipeModel>>);

  @override
  _i4.Future<List<_i2.RecipeModel>> filterByArea(String? area) =>
      (super.noSuchMethod(
            Invocation.method(#filterByArea, [area]),
            returnValue: _i4.Future<List<_i2.RecipeModel>>.value(
              <_i2.RecipeModel>[],
            ),
          )
          as _i4.Future<List<_i2.RecipeModel>>);
}

/// A class which mocks [RecipeLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecipeLocalDataSource extends _i1.Mock
    implements _i6.RecipeLocalDataSource {
  MockRecipeLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> cacheRecipes(List<_i2.RecipeModel>? recipes) =>
      (super.noSuchMethod(
            Invocation.method(#cacheRecipes, [recipes]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.RecipeModel>> getCachedRecipes() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedRecipes, []),
            returnValue: _i4.Future<List<_i2.RecipeModel>>.value(
              <_i2.RecipeModel>[],
            ),
          )
          as _i4.Future<List<_i2.RecipeModel>>);

  @override
  _i4.Future<void> addToFavorites(String? recipeId) =>
      (super.noSuchMethod(
            Invocation.method(#addToFavorites, [recipeId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> removeFromFavorites(String? recipeId) =>
      (super.noSuchMethod(
            Invocation.method(#removeFromFavorites, [recipeId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<String>> getFavorites() =>
      (super.noSuchMethod(
            Invocation.method(#getFavorites, []),
            returnValue: _i4.Future<List<String>>.value(<String>[]),
          )
          as _i4.Future<List<String>>);

  @override
  _i4.Future<bool> isFavorite(String? recipeId) =>
      (super.noSuchMethod(
            Invocation.method(#isFavorite, [recipeId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> cacheRecipeDetails(_i2.RecipeModel? recipe) =>
      (super.noSuchMethod(
            Invocation.method(#cacheRecipeDetails, [recipe]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.RecipeModel?> getCachedRecipeDetails(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedRecipeDetails, [id]),
            returnValue: _i4.Future<_i2.RecipeModel?>.value(),
          )
          as _i4.Future<_i2.RecipeModel?>);
}
