// Mocks generated by Mockito 5.4.6 from annotations
// in recipe/test/features/recipes/presentation/pages/recipe_list_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;

import 'package:flutter_bloc/flutter_bloc.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:recipe/features/recipes/domain/usecases/get_areas.dart' as _i4;
import 'package:recipe/features/recipes/domain/usecases/get_categories.dart'
    as _i3;
import 'package:recipe/features/recipes/domain/usecases/get_favorites.dart'
    as _i6;
import 'package:recipe/features/recipes/domain/usecases/get_recipes.dart'
    as _i2;
import 'package:recipe/features/recipes/domain/usecases/toggle_favorite_status.dart'
    as _i7;
import 'package:recipe/features/recipes/presentation/bloc/favorites/favorites_bloc.dart'
    as _i8;
import 'package:recipe/features/recipes/presentation/bloc/recipe_list/recipe_list_bloc.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGetRecipes_0 extends _i1.SmartFake implements _i2.GetRecipes {
  _FakeGetRecipes_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetCategories_1 extends _i1.SmartFake implements _i3.GetCategories {
  _FakeGetCategories_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetAreas_2 extends _i1.SmartFake implements _i4.GetAreas {
  _FakeGetAreas_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRecipeListState_3 extends _i1.SmartFake
    implements _i5.RecipeListState {
  _FakeRecipeListState_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetFavorites_4 extends _i1.SmartFake implements _i6.GetFavorites {
  _FakeGetFavorites_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeToggleFavoriteStatus_5 extends _i1.SmartFake
    implements _i7.ToggleFavoriteStatus {
  _FakeToggleFavoriteStatus_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFavoritesState_6 extends _i1.SmartFake
    implements _i8.FavoritesState {
  _FakeFavoritesState_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RecipeListBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecipeListBloc extends _i1.Mock implements _i5.RecipeListBloc {
  MockRecipeListBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetRecipes get getRecipes =>
      (super.noSuchMethod(
            Invocation.getter(#getRecipes),
            returnValue: _FakeGetRecipes_0(
              this,
              Invocation.getter(#getRecipes),
            ),
          )
          as _i2.GetRecipes);

  @override
  _i3.GetCategories get getCategories =>
      (super.noSuchMethod(
            Invocation.getter(#getCategories),
            returnValue: _FakeGetCategories_1(
              this,
              Invocation.getter(#getCategories),
            ),
          )
          as _i3.GetCategories);

  @override
  _i4.GetAreas get getAreas =>
      (super.noSuchMethod(
            Invocation.getter(#getAreas),
            returnValue: _FakeGetAreas_2(this, Invocation.getter(#getAreas)),
          )
          as _i4.GetAreas);

  @override
  _i5.RecipeListState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeRecipeListState_3(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i5.RecipeListState);

  @override
  _i9.Stream<_i5.RecipeListState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i9.Stream<_i5.RecipeListState>.empty(),
          )
          as _i9.Stream<_i5.RecipeListState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void add(_i5.RecipeListEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i5.RecipeListEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i5.RecipeListState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i5.RecipeListEvent>(
    _i10.EventHandler<E, _i5.RecipeListState>? handler, {
    _i10.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i10.Transition<_i5.RecipeListEvent, _i5.RecipeListState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  _i9.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  void onChange(_i10.Change<_i5.RecipeListState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [FavoritesBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockFavoritesBloc extends _i1.Mock implements _i8.FavoritesBloc {
  MockFavoritesBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.GetFavorites get getFavorites =>
      (super.noSuchMethod(
            Invocation.getter(#getFavorites),
            returnValue: _FakeGetFavorites_4(
              this,
              Invocation.getter(#getFavorites),
            ),
          )
          as _i6.GetFavorites);

  @override
  _i7.ToggleFavoriteStatus get toggleFavoriteStatus =>
      (super.noSuchMethod(
            Invocation.getter(#toggleFavoriteStatus),
            returnValue: _FakeToggleFavoriteStatus_5(
              this,
              Invocation.getter(#toggleFavoriteStatus),
            ),
          )
          as _i7.ToggleFavoriteStatus);

  @override
  _i8.FavoritesState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeFavoritesState_6(this, Invocation.getter(#state)),
          )
          as _i8.FavoritesState);

  @override
  _i9.Stream<_i8.FavoritesState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i9.Stream<_i8.FavoritesState>.empty(),
          )
          as _i9.Stream<_i8.FavoritesState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void add(_i8.FavoritesEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i8.FavoritesEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i8.FavoritesState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i8.FavoritesEvent>(
    _i10.EventHandler<E, _i8.FavoritesState>? handler, {
    _i10.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i10.Transition<_i8.FavoritesEvent, _i8.FavoritesState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  _i9.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  void onChange(_i10.Change<_i8.FavoritesState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}
